version: '3.9'

services:
  wordpress:
    image: wordpress:fpm-alpine
    container_name: wp-wordpress
    restart: unless-stopped
    depends_on:
      - mariadb
    env_file:
      - .env
    environment:
      - WORDPRESS_DB_HOST=${WORDPRESS_DB_HOST}
      - WORDPRESS_DB_NAME=${WORDPRESS_DB_NAME}
      - WORDPRESS_DB_USER=${WORDPRESS_DB_USER}
      - WORDPRESS_DB_PASSWORD=${WORDPRESS_DB_PASSWORD} 
    volumes:
      - ./wordpress:/var/www/html
    networks:
      - default

  wp-cli:
    image: wordpress:cli
    container_name: wp-cli
    restart: unless-stopped
    depends_on:
      - mariadb
      - wordpress
    user: 1000:1000
    command: tail -f /dev/null
    env_file:
      - .env
    environment:
      - WORDPRESS_DB_HOST=${WORDPRESS_DB_HOST}
      - WORDPRESS_DB_NAME=${WORDPRESS_DB_NAME}
      - WORDPRESS_DB_USER=${WORDPRESS_DB_USER}
      - WORDPRESS_DB_PASSWORD=${WORDPRESS_DB_PASSWORD} 
    volumes:
      - ./wordpress:/var/www/html
    networks:
      - default

  mariadb:
    image: mariadb:11.1.2
    container_name: wp-mariadb
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - ./mariadb:/var/lib/mysql
    networks:
      - default

  redis:
    image: redis:7.2.1-alpine
    container_name: wp-redis
    restart: unless-stopped
    command: redis-server --save 60 1 --loglevel warning
    volumes:
      - ./redis:/data
    networks:
      - default

  nginx:
    image: nginx:1.25.2-alpine
    container_name: wp-nginx
    restart: unless-stopped
    depends_on:
      - wordpress
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./wordpress:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/logs:/var/log/nginx
      - ./ssl:/etc/ssl:ro
    networks:
      - default

volumes:
  wordpress:
  mariadb:
  nginx:

networks:
  default:
    name: wordpress-default
    driver: bridge
